@startuml
(1) -- (0): 23
(2) -- (0): 21
(2) -- (1): 16
(3) -- (0): 23
(3) -- (1): 14
(3) -- (2): 26
(4) -- (0): 26
(4) -- (1): 18
(4) -- (2): 20
(4) -- (3): 19
(0) #gray
(0) -[#red]-> (2)
(2) -[#red]-> (1)
(1) -[#red]-> (3)
(3) -[#red]-> (4)
(4) -[#red]-> (0)
(0) #gray
(0) -[#blue]-> (1)
(1) -[#blue]-> (3)
(3) -[#blue]-> (4)
(4) -[#blue]-> (2)
(2) -[#blue]-> (0)
@enduml
